import type { CatalogEntry } from "./catalog";

/**
 * The Recommended shelf: official MCP servers, each URL copied from the
 * vendor's own documentation (the `docs` link on the entry) on `verifiedAt`.
 * Nothing here is taken from a directory or a registry listing. A vendor whose
 * docs did not state an endpoint, or only offered a docs-search server, is left
 * out rather than guessed. `tests/catalog.test.ts` runs every entry through the
 * same validation a team catalogue gets (https only, no literal secrets).
 *
 * Auth: "oauth" means the editor signs in (Connect OAuth); several of these
 * also accept a key in a header, which the docs link explains. "header" means
 * the vendor's docs only offer a key in a header; "env" is the same for a
 * command server. Placeholders are `{INPUT}`.
 */
const VERIFIED = "2026-09-24";

const oauth = (entry: Omit<CatalogEntry, "auth" | "transport" | "verifiedAt">): CatalogEntry => ({
  ...entry,
  transport: "http",
  auth: "oauth",
  verifiedAt: VERIFIED,
});

export const CURATED_CATALOG: CatalogEntry[] = [
  // ---------------------------------------------------------- developer tools
  oauth({
    id: "github",
    name: "GitHub",
    publisher: "GitHub",
    description: "Repositories, issues, pull requests and Actions.",
    category: "developer",
    url: "https://api.githubcopilot.com/mcp/",
    docs: "https://github.com/github/github-mcp-server",
  }),
  oauth({
    id: "sentry",
    name: "Sentry",
    publisher: "Sentry",
    description: "Errors, issues and performance data from your Sentry projects.",
    category: "developer",
    url: "https://mcp.sentry.dev/mcp",
    docs: "https://mcp.sentry.dev/",
  }),
  oauth({
    id: "vercel",
    name: "Vercel",
    publisher: "Vercel",
    description: "Projects, deployments, logs and docs search.",
    category: "developer",
    url: "https://mcp.vercel.com",
    docs: "https://vercel.com/docs/agent-resources/vercel-mcp",
  }),
  oauth({
    id: "supabase",
    name: "Supabase",
    publisher: "Supabase",
    description: "Databases, migrations, edge functions and logs.",
    category: "data",
    url: "https://mcp.supabase.com/mcp",
    docs: "https://supabase.com/docs/guides/getting-started/mcp",
  }),
  oauth({
    id: "neon",
    name: "Neon",
    publisher: "Neon",
    description: "Serverless Postgres projects, branches and queries.",
    category: "data",
    url: "https://mcp.neon.tech/mcp",
    docs: "https://neon.com/docs/ai/neon-mcp-server",
  }),
  oauth({
    id: "cloudflare-docs",
    name: "Cloudflare Docs",
    publisher: "Cloudflare",
    description: "Search Cloudflare's developer documentation.",
    category: "docs",
    url: "https://docs.mcp.cloudflare.com/mcp",
    docs: "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/",
  }),
  oauth({
    id: "cloudflare-bindings",
    name: "Cloudflare Workers Bindings",
    publisher: "Cloudflare",
    description: "Workers, KV, R2, D1 and other bindings in your account.",
    category: "developer",
    url: "https://bindings.mcp.cloudflare.com/mcp",
    docs: "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/",
  }),
  oauth({
    id: "cloudflare-observability",
    name: "Cloudflare Observability",
    publisher: "Cloudflare",
    description: "Workers logs and analytics for debugging.",
    category: "developer",
    url: "https://observability.mcp.cloudflare.com/mcp",
    docs: "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/",
  }),
  {
    id: "context7",
    name: "Context7",
    publisher: "Upstash",
    description: "Up-to-date library documentation for coding agents. A key is optional (higher rate limits).",
    category: "docs",
    transport: "http",
    url: "https://mcp.context7.com/mcp",
    auth: "none",
    docs: "https://github.com/upstash/context7",
    verifiedAt: VERIFIED,
  },
  {
    id: "microsoft-learn",
    name: "Microsoft Learn",
    publisher: "Microsoft",
    description: "Search and read Microsoft's official documentation and code samples.",
    category: "docs",
    transport: "http",
    url: "https://learn.microsoft.com/api/mcp",
    auth: "none",
    docs: "https://learn.microsoft.com/en-us/training/support/mcp",
    verifiedAt: VERIFIED,
  },
  {
    id: "playwright",
    name: "Playwright",
    publisher: "Microsoft",
    description: "Drive a real browser: navigate, click, fill forms, take snapshots.",
    category: "developer",
    transport: "stdio",
    command: "npx",
    args: ["@playwright/mcp@latest"],
    auth: "none",
    docs: "https://github.com/microsoft/playwright-mcp",
    verifiedAt: VERIFIED,
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    publisher: "DigitalOcean",
    description: "Apps, droplets, databases and other DigitalOcean resources.",
    category: "developer",
    transport: "stdio",
    command: "npx",
    // `latest`: the one word packageProblems lets a recommended entry use instead of an exact version.
    args: ["@digitalocean/mcp@latest"],
    env: { DIGITALOCEAN_API_TOKEN: "{DIGITALOCEAN_API_TOKEN}" },
    inputs: [{ id: "DIGITALOCEAN_API_TOKEN", label: "API token", secret: true, required: true, hint: "From the DigitalOcean control panel → API." }],
    auth: "env",
    docs: "https://github.com/digitalocean-labs/mcp-digitalocean",
    verifiedAt: VERIFIED,
  },
  oauth({
    id: "posthog",
    name: "PostHog",
    publisher: "PostHog",
    description: "Product analytics, feature flags, experiments and errors.",
    category: "analytics",
    url: "https://mcp.posthog.com/mcp",
    docs: "https://posthog.com/docs/model-context-protocol",
  }),
  oauth({
    id: "stripe",
    name: "Stripe",
    publisher: "Stripe",
    description: "Customers, payments, subscriptions and Stripe's docs.",
    category: "payments",
    url: "https://mcp.stripe.com",
    docs: "https://docs.stripe.com/mcp",
  }),

  // ------------------------------------------------------------- work tracking
  oauth({
    id: "linear",
    name: "Linear",
    publisher: "Linear",
    description: "Issues, projects and cycles.",
    category: "productivity",
    url: "https://mcp.linear.app/mcp",
    docs: "https://linear.app/docs/mcp",
  }),
  oauth({
    id: "atlassian",
    name: "Atlassian",
    publisher: "Atlassian",
    description: "Jira issues and Confluence pages.",
    category: "productivity",
    url: "https://mcp.atlassian.com/v2/mcp",
    docs: "https://support.atlassian.com/atlassian-rovo-mcp-server/docs/getting-started-with-the-atlassian-remote-mcp-server/",
  }),
  oauth({
    id: "asana",
    name: "Asana",
    publisher: "Asana",
    description: "Tasks, projects and goals.",
    category: "productivity",
    url: "https://mcp.asana.com/v2/mcp",
    docs: "https://developers.asana.com/docs/using-asanas-mcp-server",
  }),
  oauth({
    id: "notion",
    name: "Notion",
    publisher: "Notion",
    description: "Search, read and update pages and databases.",
    category: "productivity",
    url: "https://mcp.notion.com/mcp",
    docs: "https://developers.notion.com/docs/get-started-with-mcp",
  }),
  oauth({
    id: "airtable",
    name: "Airtable",
    publisher: "Airtable",
    description: "Bases, tables and records.",
    category: "data",
    url: "https://mcp.airtable.com/mcp",
    docs: "https://support.airtable.com/docs/using-the-airtable-mcp-server",
  }),
  oauth({
    id: "jam",
    name: "Jam",
    publisher: "Jam",
    description: "Bug reports with console logs, network requests and repro steps.",
    category: "developer",
    url: "https://mcp.jam.dev/mcp",
    docs: "https://jam.dev/docs/debug-a-jam/mcp",
  }),
  oauth({
    id: "zapier",
    name: "Zapier",
    publisher: "Zapier",
    description: "Actions across thousands of apps you connect in Zapier.",
    category: "automation",
    url: "https://mcp.zapier.com/api/v1/connect",
    docs: "https://docs.zapier.com/mcp/overview/how-connections-work",
  }),

  // ------------------------------------------------------------------- design
  oauth({
    id: "figma",
    name: "Figma",
    publisher: "Figma",
    description: "Design context, variables and code from Figma files.",
    category: "design",
    url: "https://mcp.figma.com/mcp",
    docs: "https://developers.figma.com/docs/figma-mcp-server/remote-server-installation/",
  }),
  {
    id: "heroui-pro",
    name: "HeroUI Pro",
    publisher: "HeroUI",
    description: "HeroUI and HeroUI Pro component docs, styles and source.",
    category: "design",
    transport: "http",
    url: "https://mcp.heroui.pro/mcp",
    headers: { "x-heroui-personal-token": "{HEROUI_PERSONAL_TOKEN}" },
    inputs: [{ id: "HEROUI_PERSONAL_TOKEN", label: "Personal token", secret: true, required: true, hint: "From heroui.pro/dashboard." }],
    auth: "header",
    docs: "https://heroui.pro/docs/react/getting-started/mcp-server",
    verifiedAt: VERIFIED,
  },
  oauth({
    id: "relume",
    name: "Relume Library",
    publisher: "Relume",
    description: "Search and pull Relume's 1,000+ web components into a project.",
    category: "design",
    url: "https://relume-library-mcp.relume.io/mcp",
    docs: "https://www.relume.ai/relume-library-mcp",
  }),

  // ------------------------------------------------------ customers and support
  oauth({
    id: "attio",
    name: "Attio",
    publisher: "Attio",
    description: "CRM records, lists, notes and tasks.",
    category: "crm",
    url: "https://mcp.attio.com/mcp",
    docs: "https://docs.attio.com/mcp/overview",
  }),
  oauth({
    id: "intercom",
    name: "Intercom (US)",
    publisher: "Intercom",
    description: "Conversations, contacts and tickets in a US workspace.",
    category: "support",
    url: "https://mcp.intercom.com/mcp",
    docs: "https://developers.intercom.com/docs/guides/mcp",
  }),
  oauth({
    id: "intercom-eu",
    name: "Intercom (EU)",
    publisher: "Intercom",
    description: "Conversations, contacts and tickets in an EU workspace.",
    category: "support",
    url: "https://mcp.eu.intercom.com/mcp",
    docs: "https://developers.intercom.com/docs/guides/mcp",
  }),
  oauth({
    id: "gleap",
    name: "Gleap",
    publisher: "Gleap",
    description: "Support tickets, contacts, help center and feature requests.",
    category: "support",
    url: "https://mcp.gleap.io/mcp",
    docs: "https://www.gleap.ai/mcp",
  }),
  oauth({
    id: "customerio",
    name: "Customer.io (US)",
    publisher: "Customer.io",
    description: "Campaigns, segments and people in a US workspace.",
    category: "marketing",
    url: "https://mcp.customer.io/mcp",
    docs: "https://docs.customer.io/ai/mcp/get-started/",
  }),
  oauth({
    id: "customerio-eu",
    name: "Customer.io (EU)",
    publisher: "Customer.io",
    description: "Campaigns, segments and people in an EU workspace.",
    category: "marketing",
    url: "https://mcp-eu.customer.io/mcp",
    docs: "https://docs.customer.io/ai/mcp/get-started/",
  }),
  {
    id: "justcall",
    name: "JustCall",
    publisher: "JustCall",
    description: "Calls, SMS, transcripts and call analytics.",
    category: "support",
    transport: "http",
    url: "https://mcp.justcall.host/mcp",
    headers: { Authorization: "Bearer {JUSTCALL_API_KEY}:{JUSTCALL_API_SECRET}" },
    inputs: [
      { id: "JUSTCALL_API_KEY", label: "API key", secret: true, required: true, hint: "JustCall dashboard → APIs and webhooks." },
      { id: "JUSTCALL_API_SECRET", label: "API secret", secret: true, required: true },
    ],
    auth: "header",
    docs: "https://github.com/saaslabsco/justcall-mcp-server",
    verifiedAt: VERIFIED,
  },
];
